export const HAPPYCHAT_CONNECTION_STATUS_CONNECTING = 'connecting';
export const HAPPYCHAT_CONNECTION_STATUS_CONNECTED = 'connected';
export const HAPPYCHAT_CONNECTION_STATUS_DISCONNECTED = 'disconnected';
